# Generated by Django 3.0.5 on 2020-04-19 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200419_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonesave',
            name='stud_class',
            field=models.IntegerField(default=1),
        ),
    ]
