# Generated by Django 3.0.5 on 2020-04-19 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0002_register'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Register',
        ),
    ]
