# Generated by Django 3.0.5 on 2020-04-23 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0003_delete_register'),
    ]

    operations = [
        migrations.CreateModel(
            name='CLass_1',
            fields=[
                ('s_no', models.AutoField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=100)),
                ('file_link', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='CLass_10',
            fields=[
                ('s_no', models.AutoField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=100)),
                ('file_link', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='CLass_2',
            fields=[
                ('s_no', models.AutoField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=100)),
                ('file_link', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='CLass_3',
            fields=[
                ('s_no', models.AutoField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=100)),
                ('file_link', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='CLass_4',
            fields=[
                ('s_no', models.AutoField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=100)),
                ('file_link', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='CLass_5',
            fields=[
                ('s_no', models.AutoField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=100)),
                ('file_link', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='CLass_6',
            fields=[
                ('s_no', models.AutoField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=100)),
                ('file_link', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='CLass_7',
            fields=[
                ('s_no', models.AutoField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=100)),
                ('file_link', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='CLass_8',
            fields=[
                ('s_no', models.AutoField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=100)),
                ('file_link', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='CLass_9',
            fields=[
                ('s_no', models.AutoField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=100)),
                ('file_link', models.CharField(max_length=500)),
            ],
        ),
    ]
